/* ============================================================
   pages/index.js — t-template-B main page swipers
   Slides are generated by index-mapper before this function is called.
   ============================================================ */
window.initIndexSwipers = function () {
  if (typeof Swiper === 'undefined' || !window.TplSwiper) return;

  // 원본 메인비주얼은 자동 전환이 없다 (loop:false, autoplay 없음) — 화살표로만 넘긴다
  var indexVisual = window.TplSwiper.init('indexVisual', '.main_visual_box .swiper-container', {
    spaceBetween: 0,
    loop: false,
    navigation: {
      nextEl: '.main_visual_box .swiper-button-next',
      prevEl: '.main_visual_box .swiper-button-prev'
    }
  });

  var visualPrev = document.querySelector('.main_visual_box .swiper-button-prev');
  var visualNext = document.querySelector('.main_visual_box .swiper-button-next');
  if (indexVisual && visualPrev && visualNext) {
    visualPrev.onclick = function (e) {
      e.preventDefault();
      indexVisual.slidePrev();
    };
    visualNext.onclick = function (e) {
      e.preventDefault();
      indexVisual.slideNext();
    };
  }

  // 객실 카드: 데스크톱 4장 (객실이 4개 미만이면 3장)
  var indexRoomPerView = window.TplSwiper.roomPerView('.room_list_sld');
  window.TplSwiper.init('indexRoom', '.room_list_sld', {
    slidesPerView: indexRoomPerView,
    spaceBetween: 30,
    loop: window.TplSwiper.shouldLoop('.room_list_sld', indexRoomPerView),
    navigation: {
      nextEl: '.room_list_sld .swiper-button-next',
      prevEl: '.room_list_sld .swiper-button-prev'
    },
    breakpoints: {
      280: { slidesPerView: 1, spaceBetween: 10 },
      640: { slidesPerView: 2, spaceBetween: 10 },
      768: { slidesPerView: 2, spaceBetween: 20 },
      980: { slidesPerView: indexRoomPerView, spaceBetween: 20 },
      1451: { slidesPerView: indexRoomPerView, spaceBetween: 30 }
    }
  });

  // 원본 배너 슬라이더도 자동 전환이 없다
  window.TplSwiper.init('indexBnr', '.bnr_sld .spe_list .swiper-container', {
    slidesPerView: 1,
    spaceBetween: 0,
    loop: false,
    navigation: {
      nextEl: '.bnr_sld .spe_list .swiper-button-next',
      prevEl: '.bnr_sld .spe_list .swiper-button-prev'
    }
  });
};
